config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts do
    resources :comments, only: [:index, :new, :create, :edit, :update]
  end
  resources :comments, only: [ :destroy ]
  resources :posts do
    member do
      put "vote" => "posts#vote"
    end
  end
  # get '/home', to: "pages#home"
  get '/categorized', to: "posts#categorized", as: :categorized
  get '/search_post', to: "posts#search_post", as: :search_post
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, counter_cache: true
  belongs_to :user
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  include PgSearch::Model
  pg_search_scope :search_by_title_and_content,
                  against: %i[title content],
                  using: {
                    tsearch: { prefix: true }
                  }

  belongs_to :user
  has_many :comments, dependent: :destroy

  acts_as_taggable_on :categories

  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_voter

  has_many :posts, dependent: :destroy
  has_many :comments, through: :posts

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_comment, only: %i[edit update destroy]

  def index
    @comments = policy_scope(Comment).order(created_at: :desc)
  end

  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
    authorize @comment
  end

  def create
    @comment = Comment.new(comment_params)
    @post = Post.find(params[:post_id])
    @related_posts = @post.find_related_categories.includes(:user, :taggings)
    @comment.post = @post
    @comment.user = current_user
    authorize @comment
    if @comment.save
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def edit
    # @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
    authorize @comment
  end

  def update
    # @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
    authorize @comment
    if @comment.update(comment_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    # @comment = Comment.find(params[:id])
    @post = @comment.post
    authorize @comment
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show categorized search_post]
  before_action :set_post, only: %i[show edit update destroy vote]

  def index
    @posts = policy_scope(Post).includes(:user, :taggings).order(created_at: :desc)
    # sort by having the most comment
    @hottest_posts = @posts.sort_by { |p| p.comments.size }.reverse
    # sort by number of upvotes/likes
    @popular_posts = @posts.sort_by { |post| post.get_upvotes.size }.reverse
  end

  def show
    @related_posts = @post.find_related_categories.includes(:user, :taggings)
    @comments = @post.comments.order(created_at: :desc).includes(:user)
    @comment = Comment.new
    authorize @post
    respond_to do |format|
      format.html
      format.json { render json: { post: @post } }
    end
  end

  def new
    @post = Post.new
    authorize @post
  end

  def create
    @posts = policy_scope(Post).includes(:comments).order(created_at: :desc)
    @post = Post.new(post_params)
    @post.user = current_user
    authorize @post
    @post.save!
    begin
      redirect_to post_path(@post) if @post.persisted?
      return
    rescue ActiveRecord::RecordInvalid => e
      puts e.record.errors
    end
    redirect_to posts_path
  end

  def edit
    authorize @post
  end

  def update
    authorize @post
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    authorize @post
    @post.destroy
    redirect_to posts_path
  end

  def categorized
    if params[:category].present? && params[:category].to_i != 0
      @posts = Post.tagged_with(Post.category_counts.find { |i| i.id == params[:category].to_i }.name).includes(:user, :taggings)
      @category = Post.category_counts.find { |i| i.id == params[:category].to_i }.name
    elsif params[:category].present? && params[:category].to_i == 0
      @posts = Post.tagged_with(params[:category]).includes(:user, :taggings)
      @category = params[:category]
    else
      redirect_to posts_path
    end
    authorize @posts
  end

  def search_post
    if params[:query].present?
      @posts = Post.search_by_title_and_content(params[:query]).includes(:user, :taggings)
    else
      @posts = policy_scope(Post).includes(:user, :taggings).order(created_at: :desc)
    end
    @query = params[:query]
    authorize @posts
  end

  def vote
    @related_posts = @post.find_related_categories
    @comments = @post.comments.reverse
    @comment = Comment.new
    if params[:format] == 'upvote'
      @post.upvote_by current_user
    elsif params[:format] == 'downvote'
      @post.downvote_by current_user
    end
    authorize @post
    redirect_to post_path(@post)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, category_list: [])
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.haml
.row
  .col-xs-12.col-sm-6.offset-sm-3
    .post-item-form
      = simple_form_for ([ @post, @comment ]) do |f|
        = f.input :content
        = f.submit  "Add Comment", class: "btn btn-primary"

app/views/comments/edit.html.haml
.row.mt-5
  .col-xs-12.col-sm-6.offset-sm-3
    .post-item-form
      = link_to post_path(@post), class: "post-info-comment-count" do
        %i.fas.fa-arrow-circle-left
      .form-title
        %h3 Edit your Comment
      = simple_form_for ([ @post, @comment ]) do |f|
        = f.input :content, label: false
        .post-item-bottom
          = f.submit  "Add Comment", class: "btn btn-flat"

app/views/comments/new.html.haml
.row.mt-5
  .col-xs-12.col-sm-6.offset-sm-3
    .post-item-form
      = link_to post_path(@post), class: "post-info-comment-count" do
        %i.fas.fa-arrow-circle-left
      .form-title
        %h3 Make a Comment
      = simple_form_for [ @post, @comment ] do |f|
        = f.input :content, label: false
        .post-item-bottom
          = f.submit  "Add Comment", class: "btn btn-flat"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Yonda
    = csrf_meta_tags
    = csp_meta_tag
    / Global site tag (gtag.js) - Google Analytics
    %script{:async => "", :src => "https://www.googletagmanager.com/gtag/js?id=UA-169223340-2"}
    :javascript
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      
      gtag('config', 'UA-169223340-2');
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true
  %body
    = render 'shared/navbar'
    = render 'shared/flashes'
    = yield

app/views/pages/home.html.haml
%h1 Pages#home
%p Find me in app/views/pages/home.html.erb

app/views/posts/_form.html.haml
/ <div class="row"> offset-sm-3
.col-xs-12.col-sm-5
  .post-item-form.mt-5
    .form-title
      %h3 Make a Thread
    - collection = [ "Sports", "News", "Music" ]
    = simple_form_for(@post) do |f|
      = f.input :title, label: false, placeholder: "Title"
      = f.input :content, label: false, placeholder: "Content"
      = select_tag "post[category_list][]", options_from_collection_for_select( |
        ActsAsTaggableOn::Tag.all.order("LOWER(name) ASC"),                     |
        :name, :name),                                                          |
        class: 'select2', multiple: 'multiple'                                  |
      = f.submit "Confirm", class: "btn btn-flat-add"
/ </div>

app/views/posts/_side_bar.html.haml
.col-sm-4
  .side-bar
    .make-thread
      %h4 Anything on your mind?
      %p
        Make a thread and let's talk about it!
      = link_to "Make a thread", new_post_path, class: "btn-flat-side-bar"
    .side-bar-category
      %h3 Popular Categories:
      %ul
        - ActsAsTaggableOn::Tag.most_used(10).each do |category|
          %li
            = link_to category.name, categorized_path(category: category), class: "category-link"

app/views/posts/categorized.html.haml
.row.mt-5.pt-5
  .col-xs-12.col-sm-6.offset-sm-3
    .post-item
      = link_to posts_path, class: "post-info-comment-count" do
        %i.fas.fa-arrow-circle-left
      %span
        Search results for:
        %strong= @category
- @posts.each do |post|
  .row
    .col-xs-12.col-sm-6.offset-sm-3
      .post-item
        %div
          %small.post-info-email
            posted by:#{post.user.email}
          %h3= link_to post.title.capitalize, post_path(post), class: "post-info-title"
          - post.category_list.each do |category|
            = link_to category, categorized_path(category: category), class: "btn-ghost"
        .post-item-content
          %p= post.content
        .post-item-bottom
          %span.post-info-comment-count-index
            %i.far.fa-thumbs-up
            = post.get_upvotes.size
          %span.post-info-comment-count-index
            %i.far.fa-thumbs-down
            = post.get_downvotes.size
          = link_to post_path(post), class: "post-info-comment-count-index" do
            %i.far.fa-comment-dots
            = post.comments.count

app/views/posts/edit.html.haml
- if user_signed_in?
  .row.mt-5
    .col-xs-12.col-sm-6.offset-sm-3
      .post-item-form.mt-5
        = link_to post_path(@post), class: "post-info-comment-count" do
          %i.fas.fa-arrow-circle-left
        .form-title
          %h3 Edit your post
        - collection = [ "Sports", "News", "Music" ]
        = simple_form_for(@post) do |f|
          = f.input :title
          = f.input :content
          = select_tag "post[category_list][]", options_from_collection_for_select( |
            ActsAsTaggableOn::Tag.all.order("LOWER(name) ASC"),                     |
            :name, :name),                                                          |
            class: 'select2', multiple: 'multiple'                                  |
          = f.submit "Confirm", class: "btn btn-flat-add"

app/views/posts/index.html.haml
.container.mt-5.pt-5
  .row.mt-5
    %ul#pills-tab.nav.nav-pills.mb-1.ml-4{:role => "tablist"}
      %li.nav-item.mr-2
        %a#pills-newest-tab.nav-link.active{"aria-controls" => "pills-newest", "aria-selected" => "true", "data-toggle" => "pill", :href => "#pills-newest", :role => "tab"} Newest
      %li.nav-item.mr-2
        %a#pills-hottest-tab.nav-link{"aria-controls" => "pills-hottest", "aria-selected" => "false", "data-toggle" => "pill", :href => "#pills-hottest", :role => "tab"} Hottest
      %li.nav-item.mr-2
        %a#pills-popular-tab.nav-link{"aria-controls" => "pills-popular", "aria-selected" => "false", "data-toggle" => "pill", :href => "#pills-popular", :role => "tab"} Most liked
  .row
    .col-sm-8
      .row
        #pills-tabContent.tab-content
          #pills-newest.tab-pane.fade.show.active{"aria-labelledby" => "pills-newest-tab", :role => "tabpanel"}
            .col-sm-12
              - @posts.each do |post|
                .post-item
                  %div
                    %small.post-info-email
                      posted by:#{post.user.email}
                    %h3= link_to post.title.capitalize, post_path(post), class: "post-info-title"
                    - post.category_list.each do |category|
                      = link_to category, categorized_path(category: category), class: "btn-ghost"
                  .post-item-content
                    %p= post.content
                  .post-item-bottom
                    %span.post-info-comment-count-index
                      %i.far.fa-thumbs-up
                      = post.get_upvotes.size
                    %span.post-info-comment-count-index
                      %i.far.fa-thumbs-down
                      = post.get_downvotes.size
                    = link_to post_path(post), class: "post-info-comment-count-index" do
                      %i.far.fa-comment-dots
                      = post.comments.count
          #pills-hottest.tab-pane.fade{"aria-labelledby" => "pills-hottest-tab", :role => "tabpanel"}
            .col-sm-12
              - @hottest_posts.each do |post|
                .post-item
                  %div
                    %small.post-info-email
                      posted by:#{post.user.email}
                    %h3= link_to post.title.capitalize, post_path(post), class: "post-info-title"
                    - post.category_list.each do |category|
                      = link_to category, categorized_path(category: category), class: "btn-ghost"
                  .post-item-content
                    %p= post.content
                  .post-item-bottom
                    %span.post-info-comment-count-index
                      %i.far.fa-thumbs-up
                      = post.get_upvotes.size
                    %span.post-info-comment-count-index
                      %i.far.fa-thumbs-down
                      = post.get_downvotes.size
                    = link_to post_path(post), class: "post-info-comment-count-index" do
                      %i.far.fa-comment-dots
                      = post.comments.count
          #pills-popular.tab-pane.fade{"aria-labelledby" => "pills-popular-tab", :role => "tabpanel"}
            .col-sm-12
              - @popular_posts.each do |post|
                .post-item
                  %div
                    %small.post-info-email
                      posted by:#{post.user.email}
                    %h3= link_to post.title.capitalize, post_path(post), class: "post-info-title"
                    - post.category_list.each do |category|
                      = link_to category, categorized_path(category: category), class: "btn-ghost"
                  .post-item-content
                    %p= post.content
                  .post-item-bottom
                    %span.post-info-comment-count-index
                      %i.far.fa-thumbs-up
                      = post.get_upvotes.size
                    %span.post-info-comment-count-index
                      %i.far.fa-thumbs-down
                      = post.get_downvotes.size
                    = link_to post_path(post), class: "post-info-comment-count-index" do
                      %i.far.fa-comment-dots
                      = post.comments.count
    = render 'side_bar'

app/views/posts/new.html.haml
/ 
- if user_signed_in?
  .row.mt-5.pt-5
    .col-xs-12.col-sm-6.offset-sm-3
      .post-item-form.mt-5
        = link_to posts_path, class: "post-info-comment-count" do
          %i.fas.fa-arrow-circle-left
        .form-title
          %h3 Make a Thread
        - collection = [ "Sports", "News", "Music" ]
        = simple_form_for(@post) do |f|
          = f.input :title, label: false
          = f.input :content, label: false
          = select_tag "post[category_list][]", options_from_collection_for_select( |
            ActsAsTaggableOn::Tag.all.order("LOWER(name) ASC"),                     |
            :name, :name),                                                          |
            class: 'select2', multiple: 'multiple'                                  |
          = f.submit "Confirm", class: "btn btn-flat-add"

app/views/posts/search.html.erb
<h2>Search results</h2>
<div class="row">
  <div class="col-xs-12 col-sm-6 offset-sm-3">
    <div class="post-item">
      <%= link_to "Back", posts_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>
<% @posts.each do |post| %>
  <div class="row">
    <div class="col-xs-12 col-sm-6 offset-sm-3">
      <div class="post-item">
        <small>posted by:<%= post.user.email %></small>
        <h3><%= link_to post.title, post_path(post) %></h3>
        <% post.category_list.each do |category| %>
          <p>
            <%= link_to category, categorized_path(category: category)  %>
          </p>
        <% end %>
        <p><%= post.content %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/search_post.html.haml
.row.mt-5.pt-5
  .col-xs-12.col-sm-6.offset-sm-3
    .post-item
      = link_to posts_path, class: "post-info-comment-count" do
        %i.fas.fa-arrow-circle-left
      %span
        Search results for:
        %strong= @query
- @posts.each do |post|
  .row
    .col-xs-12.col-sm-6.offset-sm-3
      .post-item
        %div
          %small.post-info-email
            posted by:#{post.user.email}
          %h3= link_to post.title.capitalize, post_path(post), class: "post-info-title"
          - post.category_list.each do |category|
            = link_to category, categorized_path(category: category), class: "btn-ghost"
        .post-item-content
          %p= post.content
        .post-item-bottom
          %span.post-info-comment-count-index
            %i.far.fa-thumbs-up
            = post.get_upvotes.size
          %span.post-info-comment-count-index
            %i.far.fa-thumbs-down
            = post.get_downvotes.size
          = link_to post_path(post), class: "post-info-comment-count-index" do
            %i.far.fa-comment-dots
            = post.comments.count

app/views/posts/show.html.haml
.container.mt-5.pt-5
  .row.mt-5
    .col-xs-12.col-sm-7
      .row
        .col-xs-12.col-sm-12
          .post-item
            = link_to posts_path, class: "post-info-comment-count" do
              %i.fas.fa-arrow-circle-left
            %div
              %small.post-info-email
                posted by:#{@post.user.email}
              %h2= @post.title
              - @post.category_list.each do |category|
                = link_to category, categorized_path(category: category), class: "btn-ghost"
            .post-item-content-show
              %p= @post.content
            .post-item-bottom-show{"data-controller" => "counter"}
              %div
                = link_to vote_post_path(@post, 'upvote'), method: :put, data: { target: "counter.id", action: "click->counter#refresh" }, remote: :true, class: "post-info-comment-count#{current_user.nil? ? "" : ((current_user.liked? @post) ? "-selected" : "")}", id: "upvote" do
                  %i.far.fa-thumbs-up
                  %span{"data-target" => "counter.count"}= @post.get_upvotes.size
                = link_to vote_post_path(@post, 'downvote'), method: :put, class: "post-info-comment-count#{current_user.nil? ? "" : ((current_user.disliked? @post) ? "-selected" : "")}",id: "downvote" do
                  %i.far.fa-thumbs-down
                  %span= @post.get_downvotes.size
              %div
                - if policy(@post).update?
                  = link_to edit_post_path(@post), class: "post-info-comment-count", id: "edit" do
                    %i.fas.fa-edit
                - if policy(@post).destroy?
                  = link_to post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, remote: true, class: "post-info-comment-count" do
                    %i.fas.fa-trash-alt
      .row
        .col-xs-12.col-sm-12
          .comment-item-list
            %h2 Comments
            - if !user_signed_in?
              %p
                Want to comment? Log in #{link_to "here", new_user_session_path, class: "button-link"}
            - if user_signed_in?
              .comment-item-form
                = simple_form_for([ @post, @comment ], remote: true)do |f|
                  = f.input :content, require: true, label: false, placeholder: "What's your thoughts?"
                  .post-item-bottom
                    = f.submit  "Comment", class: "btn btn-flat"
            - @comments.each do |comment|
              .comment-item
                %hr/
                %div
                  %small.post-info-email
                    commented by:#{comment.post.user.email}
                .post-item-content
                  %p= comment.content
                .post-item-bottom
                  - if policy(comment).update?
                    = link_to edit_post_comment_path(@post, comment), class: "post-info-comment-count" do
                      %i.fas.fa-edit
                  - if policy(comment).destroy?
                    = link_to comment, method: :delete, data: { confirm: "Are you sure?"}, remote: true, class: "post-info-comment-count" do
                      %i.fas.fa-trash-alt
    .col-xs-12.col-sm-5
      .row
        .col-xs-12.col-sm-12
          .post-item
            %h2 Related post:
      - @related_posts.each do |post|
        .row
          .col-xs-12.col-sm-12
            .post-item
              %div
                %small.post-info-email
                  posted by:#{post.user.email}
                %h3= link_to post.title.capitalize, post_path(post), class: "post-info-title"
                - post.category_list.each do |category|
                  = link_to category, categorized_path(category: category), class: "btn-ghost"
              .post-item-content
                %p= post.content
              .post-item-bottom
                %span.post-info-comment-count-index
                  %i.far.fa-thumbs-up
                  = post.get_upvotes.size
                %span.post-info-comment-count-index
                  %i.far.fa-thumbs-down
                  = post.get_downvotes.size
                = link_to post_path(post), class: "post-info-comment-count-index" do
                  %i.far.fa-comment-dots
                  = post.comments.count

app/views/shared/_flashes.html.haml
- if notice
  .alert.alert-info.alert-dismissible.fade.show.m-1{:role => "alert"}
    = notice
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} ×
- if alert
  .alert.alert-warning.alert-dismissible.fade.show.m-1{:role => "alert"}
    = alert
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} ×

app/views/shared/_navbar.html.haml
.navbar.fixed-top.navbar-expand-sm.navbar-light.navbar-lewagon.mb-5
  = link_to root_path, class: "navbar-brand" do
    = image_tag "yonda.png"
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  = simple_form_for :search_post, url: search_post_path, method: :get do |f|
    .search-form-control.form-group
      %input#query.form-control.string.required{:name => "query", :placeholder => "Find a thread", :type => "text"}/
      %button.btn.btn-flat{:name => "button", :type => "submit"}
        %i.fas.fa-search
        Search
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      - if user_signed_in?
        %li.nav-item
          = link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link"
      - else
        %li.nav-item
          = link_to "Login", new_user_session_path, class: "nav-link"
        %li.nav-item
          = link_to "Sign up", new_user_registration_path, class: "nav-link"